define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.loaded = 'loaded';
    exports.legendClick = 'legendClick';
    exports.load = 'load';
    exports.animationComplete = 'animationComplete';
    exports.legendRender = 'legendRender';
    exports.textRender = 'textRender';
    exports.pointRender = 'pointRender';
    exports.sharedTooltipRender = 'sharedTooltipRender';
    exports.seriesRender = 'seriesRender';
    exports.axisLabelRender = 'axisLabelRender';
    exports.axisLabelClick = 'axisLabelClick';
    exports.axisRangeCalculated = 'axisRangeCalculated';
    exports.axisMultiLabelRender = 'axisMultiLabelRender';
    exports.tooltipRender = 'tooltipRender';
    exports.chartMouseMove = 'chartMouseMove';
    exports.chartMouseClick = 'chartMouseClick';
    exports.chartDoubleClick = 'chartDoubleClick';
    exports.pointClick = 'pointClick';
    exports.pointDoubleClick = 'pointDoubleClick';
    exports.pointMove = 'pointMove';
    exports.chartMouseLeave = 'chartMouseLeave';
    exports.chartMouseDown = 'chartMouseDown';
    exports.chartMouseUp = 'chartMouseUp';
    exports.zoomComplete = 'zoomComplete';
    exports.dragComplete = 'dragComplete';
    exports.selectionComplete = 'selectionComplete';
    exports.resized = 'resized';
    exports.beforeResize = 'beforeResize';
    exports.beforePrint = 'beforePrint';
    exports.annotationRender = 'annotationRender';
    exports.scrollStart = 'scrollStart';
    exports.scrollEnd = 'scrollEnd';
    exports.scrollChanged = 'scrollChanged';
    exports.stockEventRender = 'stockEventRender';
    exports.multiLevelLabelClick = 'multiLevelLabelClick';
    exports.dragStart = 'dragStart';
    exports.drag = 'drag';
    exports.dragEnd = 'dragEnd';
    exports.regSub = /~\d+~/g;
    exports.regSup = /\^\d+\^/g;
    exports.beforeExport = 'beforeExport';
    exports.afterExport = 'afterExport';
    exports.bulletChartMouseClick = 'bulletChartMouseClick';
    exports.onZooming = 'onZooming';
});
